version: '3.8'
services:
  dev-db:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brothers
      POSTGRES_DB: brothersDB
    networks:
      - freecodecamp
networks:
  freecodecamp:
